export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAILURE : "LOGOUT_FAILURE",
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE",

    GET_TOKEN_SUCCESS_AFTER_LOGIN : "GET_TOKEN_SUCCESS_AFTER_LOGIN",
    IS_ADMIN : "IS_ADMIN"
}

export const tokenConstants = {
    GET_TOKEN_REQUEST : "GET_TOKEN_REQUEST",
    GET_TOKEN_SUCCESS : "GET_TOKEN_SUCCESS",
    GET_TOKEN_FAILURE :  "GET_TOKEN_FAILURE"
}

export const userDetailConstants = {
    GET_USER_DETAIL_REQUEST : "GET_USER_DETAIL_REQUEST",
    GET_USER_DETAIL_SUCCESS : "GET_USER_DETAIL_SUCCESS",
    GET_USER_DETAIL_FAILURE :  "GET_USER_DETAIL_FAILURE"
}

